apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: dev-postgres
  name: dev-postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: dev-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: dev-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: student
            - name: POSTGRES_PASSWORD
              value: postgres
          image: postgres
          name: dev-postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      restartPolicy: Always
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata
